### ISSUE TITLE
Store chunk offsets in the header

### ISSUE THREAD

**Issue by danieldk** [danieldk/rust2vec#27]
Suggested by @twuebi. This could be useful to jump to a chunk immediately, without reading preceding chunks.

**Comment by danieldk** [comment]
In order to make this work, every chunk would need to be able to report its own size. However, the storage chunks only know their size when they know their offset (to compute padding). I see two possible approaches:

1. Add a method `chunk_size` with the signature:

```rust
fn chunk_size(&self, offset: usize) -> usize;
```

I don't really like this. It's a hacky interface.

2. Require that all chunks are multiples of 4 in their sizes. So chunks that are not should add padding. However, this has the assumption that this is always the padding that we need. Suppose that in the future we'll have `f64` matrices the we alignment on a boundary of 8. Or if we have structs that need to be memory-mapped, we might need a completely different alignment. tl;dr the only future-proof approach is if every chunk is responsible for their own alignment.

So, only approach (1) is really viable.

However, I wonder if it is worth it, given the relatively modest performance gains over skipping chunk-wise.

@sebpuetz @twuebi : any opinions?

**Comment by sebpuetz** [comment]
I would just leave it as is. We can skip unwanted chunks pretty much instantly as their size is stored in the chunk header. 

Edit: Accidentally hit close and comment on my phone...

**Comment by danieldk** [comment]
Thanks for the feedback! Let's close it for real then ;).
