### ISSUE TITLE
rust2vec binary format

### ISSUE THREAD

**Issue by danieldk** [danieldk/rust2vec#3]
@sebpuetz

## Goals

I have been thinking a bit about the rust2vec binary format and want to hash out the details. The five goals of the binary format are:

1. Simple
2. Fast to parse
3. Memory-mappable matrices
4. Support for various types of embeddings: regular, sub-word, quantized, etc.
5. Existing embeddings should be convertable (word2vec binary, word2vec text, text, finalfrontier, perhaps fastText).

## Chunks

(4) is addressed by using chunks. An embedding file for embeddings with subword units could for instance have the following chunks:

* Vocabulary
* Embedding matrix
* Subword matrix

The chunk format is as follows:

- Chunk identifier: u32
- Chunk data length: u64
- Chunk data: n bytes

The chunk data length is somewhat inconvenient to precompute for some chunks (e.g. vocab). But I think it is worth it - it only requires extra computation when writing the data and allows programs to fast-forward through the file.

## Header

The header consists of:

- 3 bytes of magic: `['R', '2', 'V']`
- Format version number: u32
- Number of chunks: u32 (`n_chunks`)
- Chunk identifiers: `[u32; n_chunks]`

Some of these are oversized in their types, but we are not on a header budget, given the size of the embedding matrices. The first chunk starts immediately after the header, potential problem: memory mapping.

## Endianness

We will always assume little endian for simplicity. This is now by far the most frequent endianness across architectures. Conversions are not too expensive.

### Vocab

- Chunk identifier: 0
- Vocab length: u64 (`vocab_len`)
- `vocab_len` times:
  - word length in bytes: u32 (`word_len`)
  - `word_len` times u8.

### Embedding matrix

- Chunk identifier: 1
- Shape:
  - Rows: u64 (`n_rows`)
  - Cols: u32 (`n_cols`)
- Data type: u32 (`data_type`)
- Padding, such that data is at a multiple of `size_of::<data_type>()`.
- Data: `n_row` * `n_cols` * `sizeof(data_type)`

The motivation of specifying the data type is that we can also store quantized embedding matrices using the same chunk. Proposed encoding of data types:

```
0: i8
1: u8
2: i16
3: u16
4: i32
5: u32
6: i64
7: u64
8: i128
9: u128
10: f32
11: f64
```

## Quantized

* Chunk identifier: 3
* Projection: u8 (0/1 for false/true)
* Quantized length == number of quantizers: u32 (`n_quantizers`)
* Reconstructed vector length: u32 (`reconstructed_len`)
* Data type: u32 (`data_type`)
* Quantized data type: u32 (`quantized_data_type`)
* Padding to align the matrices to a multiple of `data_type`.
* Quantizer projection matrix (optional): `reconstructed_len` * `reconstructed_len` of `data_type`.
* Quantizer centroids: `n_quantizers` * (2^`subquantizer_bits` * `reconstructed_len`) of `data_type`.
* Number of embeddings: u64 (`n_embeds`)
* Quantized embedding matrix: `n_embeds` * `n_quantizers` of `quantized_data_type`.

**Comment by sebpuetz** [comment]
>     5. Existing embeddings should be convertable (word2vec binary, word2vec text, text, finalfrontier, perhaps fastText).
In the sense of providing some conversion methods in `rust2vec`? I'd say that would be nice to have. Conversion from other models could still be implemented fairly easy, given that the `rust2vec` format is/stays reasonably simple.
 
> ## Chunks
> 
> (4) is addressed by using chunks. An embedding file for embeddings with subword units could for instance have the following chunks:
> 
>     * Vocabulary
> 
>     * Embedding matrix
> 
>     * Subword matrix
These chunks would be predefined in `rust2vec` together with the types these chunks get deserialized into?

> ## Header
> 
> The header consists of:
> 
>     * 3 bytes of magic: `['R', '2', 'V']`
> 
>     * Format version number: u32
> 
>     * Number of chunks: u32 (`n_chunks`)
> 
>     * Chunk identifiers: `[u32; n_chunks]`
Could be nice to offer an optional field for a `String`ly descriptor of the model in the header, e.g. `descriptor_len: u32` followed by `descriptor: String`. Might not be so nice after all, as that would make mem-mapping harder.

> ## Initial chunk types
> ### Vocab
> 
>     * Chunk identifier: 0
> 
>     * Vocab length: u64 (`vocab_len`)
> 
>     * `vocab_len` times:
>       
>       * word length in bytes: u32 (`word_len`)
>       * `word_len` times u8.
>       * word count: u64

You mentioned a chunk for a subword matrix, depending on that being present or not, the deserialized vocab (and the lookup) would behave differently?

I like the concept you described, although I'd be interested in seeing how this would be realized. Would the chunks be defined as specific structs or as traits that can also be implemented by a consumer? If the consumer would be able to implement them, deserialization would also have to be handled on their side. Not sure how that would be possible.

**Comment by danieldk** [comment]
> In the sense of providing some conversion methods in `rust2vec`? I'd say that would be nice to have.

Yes, but also in the sense that these embeddings should be representable and that they should be representable without too much overhead (dummies that are not applicable to a model).

> Conversion from other models could still be implemented fairly easy, given that the `rust2vec` format is/stays reasonably simple.

Indeed.

> These chunks would be predefined in `rust2vec` together with the types these chunks get deserialized into?

Yes. They wouldn't be called chunks, but e.g. the `NdArray` embedding storage type would get serialized to a matrix chunk.

> Could be nice to offer an optional field for a `String`ly descriptor of the model in the header, e.g. `descriptor_len: u32` followed by `descriptor: String`. Might not be so nice after all, as that would make mem-mapping harder.

I think that would be useful, though for e.g. word2vec or GloVe models these would be empty. Maybe we could add a special metadata chunk when all the basic types are ready/done, we one could store attribute/value pairs. This would have the benefit that e.g. finalfrontier hyperparameters could also be stored as metadata.
 
> You mentioned a chunk for a subword matrix, depending on that being present or not, the deserialized vocab (and the lookup) would behave differently?

I am not sure yet. Maybe the subword vocab should just be a separate vocab that also stores the subword table size.

> Would the chunks be defined as specific structs or as traits that can also be implemented by a consumer?

I am still exploring the best approach, though I would like to keep it simple. Currently I am adding (private) `WriteChunk` and `ReadChunk` traits that Storage and Vocab types could implement. However the top-level serialization/deserialization would not be generic for now, so that we have control over sensible combinations.

We could consider consumer-side deserialization at some point, but I don't think it is *very* important. The number of people making custom embeddings that don't fit in the word2vec/fastText categories can probably be counted on two hands ;).

**Comment by sebpuetz** [comment]
> I think that would be useful, though for e.g. word2vec or GloVe models these would be empty. Maybe we could add a special metadata chunk when all the basic types are ready/done, we one could store attribute/value pairs. This would have the benefit that e.g. finalfrontier hyperparameters could also be stored as metadata.

Depending on how the conversion is done, e.g. using a binary or importing the conversion methods, the descriptor could either be provided as an optional commandline flag or simply set at deserialization/conversion time.
`r2v-conv model.w2v output.bin --descriptor "w2v, default settings" ` or 
```Rust
let mut r2v_model = rust2vec::read_w2v("model.w2v");
r2v_model.set_descriptor("w2v, default settings");
```

> We could consider consumer-side deserialization at some point, but I don't think it is _very_ important. The number of people making custom embeddings that don't fit in the word2vec/fastText categories can probably be counted on two hands ;).

Agreed, once other embedding types exist (and work), it should be possible to be added in the chunk-framework. So I don't think this approach would be blocking anything in the future.

**Comment by danieldk** [comment]
> `r2v-conv model.w2v output.bin --descriptor "w2v, default settings" `

Looks good.

> Agreed, once other embedding types exist (and work), it should be possible to be added in the chunk-framework. So I don't think this approach would be blocking anything in the future.

Indeed. The most important thing is to have a flexible file format. We can break the API until 1.0 ;).

**Comment by danieldk** [comment]
The first bits are in (maybe I should switch to pull requests for this repo). `Embeddings<SimpleVocab, NdArray>` can be serialized, all the serializations are tested using *write -> read* roundtrips.

Next up:

1. I will merge rust2vec-utils into this crate. Makes it easier to experiment with conversions and the new format because they can co-develop.
2. Adding `SubwordVocab` plus serialization/deserialization.

After these changes, we could add a branch to finalfrontier for conversion of finalfrontier embeddings to rust2vec.

After the dust has settled, it is probably a good idea to rename `finalfrontier-python` to `rust2vec-python` and support to support the rust2vec format instead.

**Comment by sebpuetz** [comment]
> The first bits are in (maybe I should switch to pull requests for this repo). `Embeddings<SimpleVocab, NdArray>` can be serialized, all the serializations are tested using _write -> read_ roundtrips.

Would be easier to do reviews then.

> After these changes, we could add a branch to finalfrontier for conversion of finalfrontier embeddings to rust2vec.

That means the serialization traits and chunk-types will be exposed in the API?

> After the dust has settled, it is probably a good idea to rename `finalfrontier-python` to `rust2vec-python` and support to support the rust2vec format instead.

I also thought this would be nice.

**Comment by danieldk** [comment]
> > After these changes, we could add a branch to finalfrontier for conversion of finalfrontier embeddings to rust2vec.
> 
> That means the serialization traits and chunk-types will be exposed in the API?

Not the serialization traits for the chunks, only constructors for the vocab and storage types + the serialization/deserialization trait for `Embeddings` type and its implementations.

(The chunk serialization traits are currently still `pub`, but I'll make them `pub(crate)` later.)

**Comment by sebpuetz** [comment]
> Not the serialization traits for the chunks, only constructors for the vocab and storage types + the serialization/deserialization trait for `Embeddings` type and its implementations.
> 
> (The chunk serialization traits are currently still `pub`, but I'll make them `pub(crate)` later.)

Makes sense.

Something that could also be addressed while we're discussing changes to the representation/storage of embeddings: storage alignment of the embedding matrices

**Comment by danieldk** [comment]
I just realized that we need padding before the matrix, such that the initial element of the matrix is aligned on a boundary that is a multiple of the data type size. Otherwise, we cannot correctly memory map the matrix.

This is also a bug in finalfrontier.
